services:
  backend:
    build: .
    container_name: notesapp-backend
    ports:
      - "8080:8080"
    networks:
      - app-net

  frontend:
    build: ./notesapp-frontend
    container_name: notesapp-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-net

  gitea:
    image: gitea/gitea:latest
    container_name: gitea
    ports:
      - "3000:3000"
      - "222:22"
    environment:
      - GITEA__webhook__ALLOWED_HOST_LIST=*
    volumes:
      - gitea-data:/data
    networks:
      - app-net

  jenkins:
    build: ./jenkins
    container_name: jenkins
    ports:
      - "8090:8080"
      - "50000:50000"
    environment:
      - JAVA_OPTS=-Dhttps.protocols=TLSv1.2,TLSv1.3 -Dhudson.model.DownloadService.noSignatureCheck=true
      - MAVEN_OPTS=-Dhttps.protocols=TLSv1.2,TLSv1.3
    volumes:
      - jenkins-data:/var/jenkins_home
      - C:/Users/PC/.m2:/var/jenkins_home/.m2
      - //var/run/docker.sock:/var/run/docker.sock
    networks:
      - app-net

  nexus:
    image: sonatype/nexus3:latest
    container_name: nexus
    ports:
      - "8081:8081"
      - "8082:8082"
    volumes:
      - nexus-data:/nexus-data
    networks:
      - app-net

volumes:
  gitea-data:
  jenkins-data:
  nexus-data:

networks:
  app-net:
    driver: bridge